// packages/vue/src/PanoramaViewer.vue
<template>
  <div ref="containerRef" class="panorama-viewer" :style="containerStyle"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch, computed } from 'vue';
import { PanoramaViewer as CoreViewer } from '@panorama-viewer/core';
import type { ViewerOptions, Hotspot, ViewLimits, CubemapImages } from '@panorama-viewer/core';

export interface PanoramaViewerProps {
  image: string | CubemapImages;
  format?: 'equirectangular' | 'cubemap';
  fov?: number;
  minFov?: number;
  maxFov?: number;
  autoRotate?: boolean;
  autoRotateSpeed?: number;
  gyroscope?: boolean;
  width?: string;
  height?: string;
  viewLimits?: ViewLimits | null;
  keyboardControls?: boolean;
  renderOnDemand?: boolean;
  showMiniMap?: boolean;
}

const props = withDefaults(defineProps<PanoramaViewerProps>(), {
  format: 'equirectangular',
  fov: 75,
  minFov: 30,
  maxFov: 100,
  autoRotate: false,
  autoRotateSpeed: 0.5,
  gyroscope: true,
  width: '100%',
  height: '500px',
  viewLimits: null,
  keyboardControls: true,
  renderOnDemand: true,
  showMiniMap: true,
});

const emit = defineEmits<{
  ready: [];
  error: [error: Error];
  progress: [progress: number];
  hotspotClick: [hotspot: Hotspot];
}>();

const containerRef = ref<HTMLElement>();
const viewerInstance = ref<CoreViewer | null>(null);

const containerStyle = computed(() => ({
  width: props.width,
  height: props.height,
}));

onMounted(() => {
  if (!containerRef.value) return;

  try {
    const options: ViewerOptions = {
      container: containerRef.value,
      image: props.image,
      format: props.format,
      fov: props.fov,
      minFov: props.minFov,
      maxFov: props.maxFov,
      autoRotate: props.autoRotate,
      autoRotateSpeed: props.autoRotateSpeed,
      gyroscope: props.gyroscope,
      viewLimits: props.viewLimits,
      keyboardControls: props.keyboardControls,
      renderOnDemand: props.renderOnDemand,
      onProgress: (progress: number) => emit('progress', progress),
    };

    viewerInstance.value = new CoreViewer(options);

    // Setup hotspot click listener
    containerRef.value.addEventListener('hotspotclick', ((e: CustomEvent) => {
      emit('hotspotClick', e.detail.hotspot);
    }) as EventListener);

    // Set initial minimap visibility
    if (!props.showMiniMap && viewerInstance.value) {
      viewerInstance.value.hideMiniMap();
    }

    emit('ready');
  } catch (error) {
    emit('error', error as Error);
  }
});

onUnmounted(() => {
  if (viewerInstance.value) {
    viewerInstance.value.dispose();
    viewerInstance.value = null;
  }
});

// Watch for image changes
watch(
  () => props.image,
  async (newImage) => {
    if (viewerInstance.value) {
      try {
        await viewerInstance.value.loadImage(newImage, true);
      } catch (error) {
        emit('error', error as Error);
      }
    }
  }
);

// Watch for autoRotate changes
watch(
  () => props.autoRotate,
  (newValue) => {
    if (viewerInstance.value) {
      if (newValue) {
        viewerInstance.value.enableAutoRotate();
      } else {
        viewerInstance.value.disableAutoRotate();
      }
    }
  }
);

// Watch for viewLimits changes
watch(
  () => props.viewLimits,
  (newLimits) => {
    if (viewerInstance.value) {
      viewerInstance.value.setViewLimits(newLimits);
    }
  }
);

// Watch for minimap visibility
watch(
  () => props.showMiniMap,
  (newValue) => {
    if (viewerInstance.value) {
      if (newValue) {
        viewerInstance.value.showMiniMap();
      } else {
        viewerInstance.value.hideMiniMap();
      }
    }
  }
);

// Expose methods to parent component
const loadImage = async (url: string | CubemapImages, transition = false): Promise<void> => {
  if (viewerInstance.value) {
    await viewerInstance.value.loadImage(url, transition);
  }
};

const reset = (): void => {
  if (viewerInstance.value) {
    viewerInstance.value.reset();
  }
};

const enableAutoRotate = (): void => {
  if (viewerInstance.value) {
    viewerInstance.value.enableAutoRotate();
  }
};

const disableAutoRotate = (): void => {
  if (viewerInstance.value) {
    viewerInstance.value.disableAutoRotate();
  }
};

const enableGyroscope = async (): Promise<boolean> => {
  if (viewerInstance.value) {
    return await viewerInstance.value.enableGyroscope();
  }
  return false;
};

const disableGyroscope = (): void => {
  if (viewerInstance.value) {
    viewerInstance.value.disableGyroscope();
  }
};

const getRotation = () => {
  if (viewerInstance.value) {
    return viewerInstance.value.getRotation();
  }
  return { x: 0, y: 0, z: 0 };
};

const setRotation = (x: number, y: number, z: number): void => {
  if (viewerInstance.value) {
    viewerInstance.value.setRotation(x, y, z);
  }
};

const addHotspot = (hotspot: Hotspot): void => {
  if (viewerInstance.value) {
    viewerInstance.value.addHotspot(hotspot);
  }
};

const removeHotspot = (id: string): void => {
  if (viewerInstance.value) {
    viewerInstance.value.removeHotspot(id);
  }
};

const getHotspots = (): Hotspot[] => {
  if (viewerInstance.value) {
    return viewerInstance.value.getHotspots();
  }
  return [];
};

const enterFullscreen = async (): Promise<void> => {
  if (viewerInstance.value) {
    await viewerInstance.value.enterFullscreen();
  }
};

const exitFullscreen = (): void => {
  if (viewerInstance.value) {
    viewerInstance.value.exitFullscreen();
  }
};

const isFullscreen = (): boolean => {
  if (viewerInstance.value) {
    return viewerInstance.value.isFullscreen();
  }
  return false;
};

const screenshot = (width?: number, height?: number): string => {
  if (viewerInstance.value) {
    return viewerInstance.value.screenshot(width, height);
  }
  return '';
};

const setViewLimits = (limits: ViewLimits | null): void => {
  if (viewerInstance.value) {
    viewerInstance.value.setViewLimits(limits);
  }
};

const showMiniMap = (): void => {
  if (viewerInstance.value) {
    viewerInstance.value.showMiniMap();
  }
};

const hideMiniMap = (): void => {
  if (viewerInstance.value) {
    viewerInstance.value.hideMiniMap();
  }
};

const toggleMiniMap = (): void => {
  if (viewerInstance.value) {
    viewerInstance.value.toggleMiniMap();
  }
};

defineExpose({
  loadImage,
  reset,
  enableAutoRotate,
  disableAutoRotate,
  enableGyroscope,
  disableGyroscope,
  getRotation,
  setRotation,
  addHotspot,
  removeHotspot,
  getHotspots,
  enterFullscreen,
  exitFullscreen,
  isFullscreen,
  screenshot,
  setViewLimits,
  showMiniMap,
  hideMiniMap,
  toggleMiniMap,
});
</script>

<style scoped>
.panorama-viewer {
  position: relative;
  overflow: hidden;
}
</style>

// packages/lit/src/panorama-viewer.ts
import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { PanoramaViewer as CoreViewer } from '@panorama-viewer/core';
import type { ViewerOptions, Hotspot, ViewLimits, CubemapImages } from '@panorama-viewer/core';

/**
 * Panorama Viewer Web Component
 * 
 * @element panorama-viewer
 * 
 * @attr {string} image - URL or path to the panorama image
 * @attr {string} format - Image format: 'equirectangular' or 'cubemap'
 * @attr {number} fov - Field of view in degrees (default: 75)
 * @attr {number} min-fov - Minimum field of view for zoom (default: 30)
 * @attr {number} max-fov - Maximum field of view for zoom (default: 100)
 * @attr {boolean} auto-rotate - Enable auto rotation (default: false)
 * @attr {number} auto-rotate-speed - Auto rotation speed (default: 0.5)
 * @attr {boolean} gyroscope - Enable gyroscope controls on mobile (default: true)
 * @attr {boolean} keyboard-controls - Enable keyboard controls (default: true)
 * @attr {boolean} render-on-demand - Enable render on demand (default: true)
 * @attr {boolean} show-mini-map - Show mini map (default: true)
 * @attr {string} width - Container width (default: 100%)
 * @attr {string} height - Container height (default: 500px)
 * 
 * @fires ready - Fired when the viewer is initialized
 * @fires error - Fired when an error occurs
 * @fires progress - Fired during image loading
 * @fires hotspotclick - Fired when a hotspot is clicked
 */
@customElement('panorama-viewer')
export class PanoramaViewerElement extends LitElement {
  static override styles = css`
    :host {
      display: block;
      position: relative;
    }

    .container {
      width: 100%;
      height: 100%;
      overflow: hidden;
    }
  `;

  @property({ type: String })
  image = '';

  @property({ type: String })
  format: 'equirectangular' | 'cubemap' = 'equirectangular';

  @property({ type: Number })
  fov = 75;

  @property({ type: Number, attribute: 'min-fov' })
  minFov = 30;

  @property({ type: Number, attribute: 'max-fov' })
  maxFov = 100;

  @property({ type: Boolean, attribute: 'auto-rotate' })
  autoRotate = false;

  @property({ type: Number, attribute: 'auto-rotate-speed' })
  autoRotateSpeed = 0.5;

  @property({ type: Boolean })
  gyroscope = true;

  @property({ type: Boolean, attribute: 'keyboard-controls' })
  keyboardControls = true;

  @property({ type: Boolean, attribute: 'render-on-demand' })
  renderOnDemand = true;

  @property({ type: Boolean, attribute: 'show-mini-map' })
  showMiniMap = true;

  @property({ type: String })
  width = '100%';

  @property({ type: String })
  height = '500px';

  @property({ type: Object, attribute: false })
  viewLimits: ViewLimits | null = null;

  private viewer: CoreViewer | null = null;
  private containerElement: HTMLElement | null = null;

  override render() {
    return html`
      <div class="container" style="width: ${this.width}; height: ${this.height}">
      </div>
    `;
  }

  override firstUpdated() {
    this.containerElement = this.shadowRoot?.querySelector('.container') as HTMLElement;
    
    if (this.containerElement && this.image) {
      this.initializeViewer();
    }
  }

  private initializeViewer() {
    if (!this.containerElement || !this.image) return;

    try {
      const options: ViewerOptions = {
        container: this.containerElement,
        image: this.image,
        format: this.format,
        fov: this.fov,
        minFov: this.minFov,
        maxFov: this.maxFov,
        autoRotate: this.autoRotate,
        autoRotateSpeed: this.autoRotateSpeed,
        gyroscope: this.gyroscope,
        viewLimits: this.viewLimits,
        keyboardControls: this.keyboardControls,
        renderOnDemand: this.renderOnDemand,
        onProgress: (progress: number) => {
          this.dispatchEvent(new CustomEvent('progress', { detail: { progress } }));
        },
      };

      this.viewer = new CoreViewer(options);

      // Setup hotspot click listener
      this.containerElement.addEventListener('hotspotclick', ((e: CustomEvent) => {
        this.dispatchEvent(new CustomEvent('hotspotclick', {
          detail: { hotspot: e.detail.hotspot },
        }));
      }) as EventListener);

      // Set initial minimap visibility
      if (!this.showMiniMap && this.viewer) {
        this.viewer.hideMiniMap();
      }

      this.dispatchEvent(new CustomEvent('ready'));
    } catch (error) {
      this.dispatchEvent(
        new CustomEvent('error', {
          detail: { error },
        })
      );
    }
  }

  override updated(changedProperties: Map<string, any>) {
    // Handle image changes
    if (changedProperties.has('image') && this.viewer && this.image) {
      this.viewer.loadImage(this.image, true).catch((error) => {
        this.dispatchEvent(
          new CustomEvent('error', {
            detail: { error },
          })
        );
      });
    }

    // Handle autoRotate changes
    if (changedProperties.has('autoRotate') && this.viewer) {
      if (this.autoRotate) {
        this.viewer.enableAutoRotate();
      } else {
        this.viewer.disableAutoRotate();
      }
    }

    // Handle viewLimits changes
    if (changedProperties.has('viewLimits') && this.viewer) {
      this.viewer.setViewLimits(this.viewLimits);
    }

    // Handle minimap visibility
    if (changedProperties.has('showMiniMap') && this.viewer) {
      if (this.showMiniMap) {
        this.viewer.showMiniMap();
      } else {
        this.viewer.hideMiniMap();
      }
    }
  }

  override disconnectedCallback() {
    super.disconnectedCallback();
    if (this.viewer) {
      this.viewer.dispose();
      this.viewer = null;
    }
  }

  /**
   * Load a new panorama image
   */
  public async loadImage(url: string | CubemapImages, transition = false): Promise<void> {
    if (this.viewer) {
      await this.viewer.loadImage(url, transition);
    }
  }

  /**
   * Reset camera to initial position
   */
  public reset(): void {
    if (this.viewer) {
      this.viewer.reset();
    }
  }

  /**
   * Enable auto rotation
   */
  public enableAutoRotate(): void {
    if (this.viewer) {
      this.viewer.enableAutoRotate();
    }
  }

  /**
   * Disable auto rotation
   */
  public disableAutoRotate(): void {
    if (this.viewer) {
      this.viewer.disableAutoRotate();
    }
  }

  /**
   * Enable gyroscope controls (mobile only)
   */
  public async enableGyroscope(): Promise<boolean> {
    if (this.viewer) {
      return await this.viewer.enableGyroscope();
    }
    return false;
  }

  /**
   * Disable gyroscope controls
   */
  public disableGyroscope(): void {
    if (this.viewer) {
      this.viewer.disableGyroscope();
    }
  }

  /**
   * Get the current camera rotation
   */
  public getRotation(): { x: number; y: number; z: number } {
    if (this.viewer) {
      return this.viewer.getRotation();
    }
    return { x: 0, y: 0, z: 0 };
  }

  /**
   * Set the camera rotation
   */
  public setRotation(x: number, y: number, z: number): void {
    if (this.viewer) {
      this.viewer.setRotation(x, y, z);
    }
  }

  /**
   * Add a hotspot marker
   */
  public addHotspot(hotspot: Hotspot): void {
    if (this.viewer) {
      this.viewer.addHotspot(hotspot);
    }
  }

  /**
   * Remove a hotspot by ID
   */
  public removeHotspot(id: string): void {
    if (this.viewer) {
      this.viewer.removeHotspot(id);
    }
  }

  /**
   * Get all hotspots
   */
  public getHotspots(): Hotspot[] {
    if (this.viewer) {
      return this.viewer.getHotspots();
    }
    return [];
  }

  /**
   * Enter fullscreen mode
   */
  public async enterFullscreen(): Promise<void> {
    if (this.viewer) {
      await this.viewer.enterFullscreen();
    }
  }

  /**
   * Exit fullscreen mode
   */
  public exitFullscreen(): void {
    if (this.viewer) {
      this.viewer.exitFullscreen();
    }
  }

  /**
   * Check if in fullscreen
   */
  public isFullscreen(): boolean {
    if (this.viewer) {
      return this.viewer.isFullscreen();
    }
    return false;
  }

  /**
   * Take a screenshot
   */
  public screenshot(width?: number, height?: number): string {
    if (this.viewer) {
      return this.viewer.screenshot(width, height);
    }
    return '';
  }

  /**
   * Set view limits
   */
  public setViewLimits(limits: ViewLimits | null): void {
    if (this.viewer) {
      this.viewer.setViewLimits(limits);
    }
  }

  /**
   * Show mini map
   */
  public showMiniMap(): void {
    if (this.viewer) {
      this.viewer.showMiniMap();
    }
  }

  /**
   * Hide mini map
   */
  public hideMiniMap(): void {
    if (this.viewer) {
      this.viewer.hideMiniMap();
    }
  }

  /**
   * Toggle mini map visibility
   */
  public toggleMiniMap(): void {
    if (this.viewer) {
      this.viewer.toggleMiniMap();
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'panorama-viewer': PanoramaViewerElement;
  }
}
